[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
cert_program = "6qZS7v9cEzK8bxUCdiLPCwr3GbWVuyE5w9N3oMNRrwFU"

[workspace]
members = ["programs/cert-program"]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --ignore '**/node_modules/**'"

[test]
startup_wait = 60000